[package]
name = "enterprise-facade-api"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
cw20 = "1.0.1"
cw721 = "0.16.0"
cw-asset = "2.4.0"
cw-utils = "1.0.1"
poll-engine-api = { path = "../poll-engine-api" }
enterprise-governance-controller-api = { path = "../enterprise-governance-controller-api" }
serde_with = { version = "2", features = ["json", "macros"] }
strum_macros = "0.24"
thiserror = "1"
