[package]
name = "enterprise-versioning-api"
version = "1.0.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
thiserror = "1"
