[package]
name = "multisig-membership-impl"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
cw-storage-plus = "1.0.1"
cw-utils = "1.0.1"
multisig-membership-api = { path = "../multisig-membership-api" }
itertools = "0.10.5"
thiserror = "1"
