[package]
name = "enterprise-governance-controller-api"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common"}
cosmwasm-schema = "1.1"
cosmwasm-std = "1.2.4"
cw20 = "1.0.1"
cw-asset = "2.4.0"
cw-utils = "1.0.1"
enterprise-protocol = { path = "../enterprise-protocol"}
enterprise-treasury-api = { path = "../../packages/enterprise-treasury-api" }
membership-common-api = { path = "../../packages/membership-common-api" }
multisig-membership-api = { path = "../../packages/multisig-membership-api" }
poll-engine-api = { path = "../poll-engine-api"}
serde_with = { version = "2", features = ["json", "macros"] }
strum_macros = "0.24"
thiserror = "1"