[package]
name = "membership-common"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
membership-common-api = { path = "../membership-common-api" }
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
cw-storage-plus = "1.1.0"
cw-utils = "1.0.1"
thiserror = "1"
