[package]
name = "ics721-callback-proxy-impl"
version = "1.0.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
common = { path = "../common" }
cosmwasm-std = "1"
cosmwasm-schema = "1.1"
cw721 = "0.16.0"
cw-storage-plus = "1.0.1"
cw-utils = "1.0.1"
nft-staking-api = { path = "../nft-staking-api" }
ics721-types = { path = "../ics721-types" }
ics721-callback-proxy-api = { path = "../ics721-callback-proxy-api" }
thiserror = "1"
